<a href="https://colab.research.google.com/github/Rochyala85/Data-Science-Flex/blob/main/Unidad_03_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [72]:
import numpy as np
import pandas as pd

In [73]:
list1 = np.array(range(10))
list2 = pd.Series(range(10))

In [74]:
print(list1)
print('---------')
print(list2)

[0 1 2 3 4 5 6 7 8 9]
---------
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64


In [75]:
import time

In [76]:
inicionp = time.time()

list3 = np.array(range(1000000))
print(np.mean(list3))
print(np.median(list3))

finnp = time.time()
print(finnp - inicionp)

499999.5
499999.5
0.19900035858154297


In [77]:
iniciopd = time.time()

list4 = pd.Series(range(1000000))
print(list4.mean())
print(list4.median())

finpd = time.time()
print(finpd - iniciopd)

499999.5
499999.5
0.019103288650512695


In [78]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [79]:
T = tuple(range(10))
T

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

In [80]:
import numpy as np

Npa = np.array(range(10))
Npa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
Np_cero = np.zeros(10)
Np_cero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [82]:
Np_cero_int = np.zeros(10, dtype=int)
Np_cero_int

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [83]:
Np_uno = np.ones(10)
Np_uno

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [84]:
Np_relleno = np.full(10,256)
Np_relleno

array([256, 256, 256, 256, 256, 256, 256, 256, 256, 256])

In [85]:
Np_rango = np.arange(10)
Np_rango

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
Np_random_dimensiones = np.random.randint(10, size=(3, 4))
Np_random_dimensiones

array([[7, 5, 4, 3],
       [0, 0, 9, 1],
       [2, 4, 6, 4]])

In [87]:
# Verificando el tipo de dato de array
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [88]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [89]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [90]:
arr = np.array([1, 2, 3, 4], dtype='i')
print(arr);print(arr.dtype)

[1 2 3 4]
int32


In [91]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [92]:
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [93]:
Np_cero.ndim

1

In [94]:
Np_random_dimensiones.ndim

2

In [95]:
Np_random_dimensiones.shape

(3, 4)

In [96]:
Np_random_dimensiones.size

12

In [97]:
Np_cero.dtype

dtype('float64')

In [98]:
Np_cero_int.dtype

dtype('int64')

In [99]:
Np_random_dimensiones.itemsize

8

In [100]:
Np_cero.nbytes

80

In [101]:
Np_cero_int.nbytes

80

In [102]:
rango = range(1,11)
Np_diez_numeros = np.array(rango)
Np_diez_numeros

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
Np_diez_numeros[0]

np.int64(1)

In [104]:
Np_diez_numeros[4]

np.int64(5)

In [105]:
Np_diez_numeros[-1]

np.int64(10)

In [106]:
Np_diez_numeros[-2]

np.int64(9)

In [107]:
Np_random_dimensiones

array([[7, 5, 4, 3],
       [0, 0, 9, 1],
       [2, 4, 6, 4]])

In [108]:
Np_random_dimensiones[2, 1]

np.int64(4)

In [109]:
Np_diez_numeros[:4]

array([1, 2, 3, 4])

In [110]:
Np_diez_numeros[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [111]:
Np_diez_numeros[4:7]

array([5, 6, 7])

In [112]:
Np_diez_numeros[::2]

array([1, 3, 5, 7, 9])

In [113]:
Np_diez_numeros[::-2]

array([10,  8,  6,  4,  2])

In [114]:
Np_random_dimensiones[2,]

array([2, 4, 6, 4])

In [115]:
Np_random_dimensiones[:2, :2]

array([[7, 5],
       [0, 0]])

In [116]:
Np_random_dimensiones[2, 3]

np.int64(4)

In [117]:
np.arange(1,65)
Ajedrez_64 = np.arange(1,65).reshape(8,8)
Ajedrez_64

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [118]:
Array_1 = np.random.randint(10, size=5)
Array_2 = np.random.randint(10, size=5)
Arrays_concatenados = np.concatenate([Array_1, Array_2])
Arrays_concatenados

array([9, 3, 3, 9, 1, 9, 4, 5, 6, 7])

In [119]:
Array_extra = np.array([[10],[20]])
Array_extra

array([[10],
       [20]])

In [120]:
Array_apilados_v = np.vstack([Array_extra, Array_extra])
Array_apilados_v

array([[10],
       [20],
       [10],
       [20]])

In [121]:
Array_apilados_h = np.hstack([Array_extra, Array_extra])
Array_apilados_h

array([[10, 10],
       [20, 20]])

In [122]:
Arrays_concatenados

array([9, 3, 3, 9, 1, 9, 4, 5, 6, 7])

In [123]:
Array_partido = np.split(Arrays_concatenados, [2])
Array_partido

[array([9, 3]), array([3, 9, 1, 9, 4, 5, 6, 7])]

In [124]:
Array_partido_2 = np.split(Arrays_concatenados, [3, 8])
Array_partido_2

[array([9, 3, 3]), array([9, 1, 9, 4, 5]), array([6, 7])]

In [125]:
Parte_1, Parte_2, Parte_3 = Array_partido_2
Parte_1

array([9, 3, 3])

In [126]:
Parte_2

array([9, 1, 9, 4, 5])

In [127]:
Parte_3

array([6, 7])

In [128]:
Ajedrez_partido_1 = np.hsplit(Ajedrez_64, [4])
Ajedrez_partido_1

[array([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12],
        [17, 18, 19, 20],
        [25, 26, 27, 28],
        [33, 34, 35, 36],
        [41, 42, 43, 44],
        [49, 50, 51, 52],
        [57, 58, 59, 60]]),
 array([[ 5,  6,  7,  8],
        [13, 14, 15, 16],
        [21, 22, 23, 24],
        [29, 30, 31, 32],
        [37, 38, 39, 40],
        [45, 46, 47, 48],
        [53, 54, 55, 56],
        [61, 62, 63, 64]])]

In [129]:
Ajedrez_partido_2 = np.vsplit(Ajedrez_64, [4])
Ajedrez_partido_2

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32]]),
 array([[33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64]])]

In [130]:
Array_aleatorio = np.random.randint(10, size=10)
print(Array_aleatorio)
suma = 0
for i in Array_aleatorio:
    suma += i
promedio = suma / np.size(Array_aleatorio)

[3 9 7 5 7 6 7 3 5 0]


In [131]:
Array_aleatorio.sum()

np.int64(52)

In [132]:
Array_aleatorio.mean()

np.float64(5.2)

In [133]:
Array_aleatorio.max()

np.int64(9)

In [134]:
np.median(Array_aleatorio)

np.float64(5.5)

In [135]:
np.std(Array_aleatorio)

np.float64(2.4819347291981715)

In [136]:
np.var(Array_aleatorio)

np.float64(6.160000000000001)

In [137]:
Array_1

array([9, 3, 3, 9, 1])

In [138]:
Array_2


array([9, 4, 5, 6, 7])

In [139]:
Array_1+5

array([14,  8,  8, 14,  6])

In [140]:
Array_1 + Array_2

array([18,  7,  8, 15,  8])

In [141]:
np.add(Array_1, Array_2)

array([18,  7,  8, 15,  8])

In [142]:
np.matmul(Array_1, Array_2)

np.int64(169)